class Stats::InsertStatlistAbbrService
	def initialize()
	end

	def call()
		efg = StatList.find_by_id(18)
		efg.update(abbr: "EFG%")
		ts = StatList.find_by_id(19)
		ts.update(abbr: "TS%")
		ptar = StatList.find_by_id(20)
		ptar.update(abbr: "3PAr")
		ftar = StatList.find_by_id(21)
		ftar.update(abbr: "FTAr")
		usg = StatList.find_by_id(22)
		usg.update(abbr: "USG%")
		ortg = StatList.find_by_id(23)
		ortg.update(abbr: "ORtg")
		drtg = StatList.find_by_id(24)
		drtg.update(abbr: "DRtg")
		netrtg = StatList.find_by_id(25)
		netrtg.update(abbr: "NetRtg")
		offeff = StatList.find_by_id(29)
		offeff.update(abbr: "OEff")
		defeff = StatList.find_by_id(30)
		defeff.update(abbr: "DEff")
		offreb = StatList.find_by_id(32)
		offreb.update(abbr: "ORB%")
		defreb = StatList.find_by_id(33)
		defreb.update(abbr: "DRB%")
		totreb = StatList.find_by_id(34)
		totreb.update(abbr: "TotRB%")
		stl = StatList.find_by_id(35)
		stl.update(abbr: "STL%")
		blk = StatList.find_by_id(36)
		blk.update(abbr: "BLK%")
		tov = StatList.find_by_id(37)
		tov.update(abbr: "TOV%")
		ast = StatList.find_by_id(38)
		ast.update(abbr: "AST%")
		obpm = StatList.find_by_id(39)
		obpm.update(abbr: "OBPM")
		bpm = StatList.find_by_id(41)
		bpm.update(abbr: "BPM")
		dbpm = StatList.find_by_id(40)
		dbpm.update(abbr: "DBPM")
		poss = StatList.find_by_id(42)
		poss.update(abbr: "POSS")
		pace = StatList.find_by_id(45)
		pace.update(abbr: "Pace")
		ftr = StatList.find_by_id(46)
		ftr.update(abbr: "FTr")

		fg = StatList.find_by_id(1)
		fg.update(abbr: "FG")
		ast = StatList.find_by_id(3)
		ast.update(abbr: "AST")
		oreb = StatList.find_by_id(4)
		oreb.update(abbr: "OReb")
		dreb = StatList.find_by_id(5)
		dreb.update(abbr: "DReb")
		stls = StatList.find_by_id(6)
		stls.update(abbr: "STL")
		tovs = StatList.find_by_id(7)
		tovs.update(abbr: "TOV")
		blks = StatList.find_by_id(8)
		blks.update(abbr: "BLK")
		thrptfg = StatList.find_by_id(11)
		thrptfg.update(abbr:"3PtFG" )
		ftmakes = StatList.find_by_id(13)
		ftmakes.update(abbr: "FT")
		pts = StatList.find_by_id(15)
		pts.update(abbr: "PTS")
		minutes = StatList.find_by_id(16)
		minutes.update(abbr: "MIN")
		fouls = StatList.find_by_id(17)
		fouls.update(abbr: "FLS")
		fgpct = StatList.find_by_id(26)
		fgpct.update(abbr: "FG%")
		thrpct = StatList.find_by_id(27)
		thrpct.update(abbr: "3Pt%")
		ftpct = StatList.find_by_id(28)
		ftpct.update(abbr: "FT%")
		fga = StatList.find_by_id(47)
		fga.update(abbr: "FGA")
		thrpa = StatList.find_by_id(48)
		thrpa.update(abbr: "3PA")
		fta = StatList.find_by_id(49)
		fta.update(abbr: "FTA")
		defl = StatList.find_by_id(51)
		defl.update(abbr: "DEFL")
		ast_ratio = StatList.find_by_id(50)
		ast_ratio.update(abbr: "AST Ratio")


	end

end


